### ISSUE TITLE
Unable to convert to Steam

### ISSUE THREAD

**Issue by CWO333** [ProjectCeleste/Celeste_Launcher#55]
Every time I click the Confirm dialog for converting to Steam I get: Unexpected Error occurred. Please try again or check the log files. I haven't found any log files yet. I'll provide the log if it does exist.

**Comment by martinmine** [comment]
There should be a "Logs" folder together with `Celeste Launcher.exe`. It should contain the log file with the error that is causing this issue.

**Comment by martinmine** [comment]
Thanks for reporting this issue. It turned out it was a regression error after renaming the .exe file to "Celeste Launcher.exe". This is fixed by commit https://github.com/martinmine/Celeste_Launcher/commit/45f6676300bc8ef1605833fcdb716b62e302973e and will be fixed in the next release.

**Comment by martinmine** [comment]
The error message being logged for this issue is:
```
2020-01-18 22:29:53.514 +01:00 [ERR] 
System.IO.FileNotFoundException: 
File name: 'F:\Steam\steamapps\common\Age Of Empires Online\Celeste_Launcher_Gui.exe'
   at Celeste_Public_Api.Helpers.Misc.MoveFile(String originalFilePath, String destFilePath, Boolean doBackup) in c:\projects\celeste_launcher\Libs\Celeste_Public_Api\Helpers\Misc.cs:line 47
   at Celeste_Launcher_Gui.Helpers.Steam.ConvertToSteam(String gamePath) in c:\projects\celeste_launcher\Celeste_Launcher_Gui\Helpers\Steam.cs:line 15
   at Celeste_Launcher_Gui.Windows.SteamConverterWindow.ConfirmBtnClick(Object sender, RoutedEventArgs e) in c:\projects\celeste_launcher\Celeste_Launcher_Gui\Windows\SteamConverterWindow.xaml.cs:line 51
```
